---
title: "climatedatacleaning"
output: html_document
date: "2023-07-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

getwd()
```

```{r load packages, include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)

```


```{r climate data, include=FALSE}

climate.data.DRC <- read.csv("raw/climatic-impact-data.csv", header = TRUE, check.names = F)

names(climate.data.DRC)

which( duplicated( names(climate.data.DRC) ) )

climate.data.sudkivu <- climate.data.DRC %>%
  filter(admin1Label == "Sud-kivu")

write.csv(climate.data.sudkivu, "processed/climate.data.sudkivu.csv")

```

```{r fies data, include=FALSE}

fies.data.2020.DRC <-read.csv("raw/fao_fies_data.csv", header = TRUE)

```

```{r MICS6 data, include=FALSE}

birthhistory.DRC <-read.csv("raw/UNICEF_MICS6_birthhistory.csv", header = TRUE, check.names = F)

```

```{r Maldata, include=FALSE}

sudkivu.malnutrition.may2023 <- read.csv("raw/sudkivu_malnutrition_data_may2023.csv", header = TRUE, check.names = F)

```

```{r humneedsdata, include=FALSE}

sudkivu.humanitarianneeds.nutrition <- read.csv("raw/Sudkivu_humanitarianneeds_nutritiononly_dhx_data.csv", header = TRUE, check.names = F)

```

```{r food insecurity data, include=FALSE}

acute.food.insecurity <- read.csv("raw/ipc_subnat_acute_food_insecurity.csv", header = TRUE, check.names = F)

acute.food.insecurity$`Date of analysis` <- mdy(acute.food.insecurity$`Date of analysis`)

class(acute.food.insecurity$`Date of analysis`)

acute.food.insecurity.recent <- acute.food.insecurity %>%
  select(`Date of analysis`,`Level 1`, `Area`, `Validity period`, `Phase`, `Number`, `Percentage`) %>%
  filter(`Date of analysis` > "2018-12-31" & `Date of analysis` < "2024-01-01")

acute.food.insecurity.2019 <-acute.food.insecurity.recent %>%
  filter(`Date of analysis` > "2018-12-31" & `Date of analysis` < "2020-01-01") %>%
  filter(`Level 1` == "Sud-Kivu") %>%
  filter(`Validity period` == "current")
  
abovethree.acute.food.insecrity.2019 <-acute.food.insecurity.2019 %>%
  filter(`Phase` == "3+")

acute.food.insecurity.2020 <-acute.food.insecurity.recent %>%
  filter(`Date of analysis` > "2019-12-31" & `Date of analysis` < "2021-01-01") %>%
  filter(`Level 1` == "Sud Kivu") %>%
  filter(`Validity period` == "current")
  
abovethree.acute.food.insecrity.2020 <-acute.food.insecurity.2020 %>%
  filter(`Phase` == "3+")

```

